language: c
matrix:
    include:
        - os: linux
          compiler: gcc

        - os: linux
          compiler: clang

        - os: osx
          compiler: gcc

        - os: osx
          compiler: clang

        - os: linux
          compiler: gcc
          env: CONFIGURE_OPTS=--enable-64-bit-words

        - os: linux
          compiler: clang
          env: CONFIGURE_OPTS=--enable-64-bit-words

        - os: osx
          compiler: gcc
          env: CONFIGURE_OPTS=--enable-64-bit-words

        - os: osx
          compiler: clang
          env: CONFIGURE_OPTS=--enable-64-bit-words
script:
  - ./autogen.sh && ./configure $CONFIGURE_OPTS && make && make check
